version: "3.3"
services:
  web:
    image: "aleqhub/alabuga_server:latest"
    restart: always
    ports:
      - "32097:32097"
    env_file:
      - ./.env.dev
    depends_on:
      - telegram
  telegram:
    image: "aleqhub/alabuga_telegram:latest"
    restart: always
    ports:
      - "32098:32098"
  ollama:
    image: "ollama/ollama"
    volumes: 
      - ollama_data:/root/.ollama
    restart: always
    ports:
      - "11434:11434"
volumes:
  ollama_data: